# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202309.08.0"
  
  config.vm.provider "virtualbox" do |v|
    #v.gui = true
    v.gui = false
  end
  #####################################
  config.vm.define "my1" do |mymachine|
    mymachine.vm.hostname = "my1"
    mymachine.vm.provision "shell", inline: "apt-get update"
    
    # needrestart automatically restart daemon
    mymachine.vm.provision "shell", inline: "echo \"\\\$nrconf{restart} = 'a';\" | tee /etc/needrestart/conf.d/50-autorestart.conf"
    
    # install python pip
    mymachine.vm.provision "shell", inline: "apt-get install -y python3-pip"
    
    # install jupyter
    mymachine.vm.provision "shell", inline: "pip install jupyter"
    
    # run jupyter
    mymachine.vm.provision "shell", inline: "jupyter lab --ip=* --port=8888 --IdentityProvider.token=\"\" --no-browser --allow-root --notebook-dir=/vagrant & ", run: "always"
    
    # portforwarding
    mymachine.vm.network "forwarded_port", guest: 8888, host: 8080 
  end
  #####################################


end
